### ISSUE TITLE
icon font

### ISSUE THREAD

**Issue by 970C** [chriscoyier/CSS-Tricks-v10#21] opened 2012-09-06 15:47 UTC
The icon font for the main navigation is not showing up in FF 15

**Comment by danielcha** [comment] 2012-09-06 15:56
nor in IE9

**Comment by OllyHodgson** [comment] 2012-09-06 16:07
This is a duplicate of issue #2.

**Comment by chriscoyier** [comment] 2012-09-06 16:08
Fixed!

Er, well, in Firefox at least. Let me know about IE 9.

**Closed as completed by chriscoyier** 2012-09-06 16:08 UTC

**Comment by danielcha** [comment] 2012-09-06 16:12
Wow quick fix Chris! Awesome

After a quick cache refresh on IE9 it also looks like it is suppose to :-)

Note: I only used IE9 because I wanted to see the new design with crisp font-rendering, which sucks for Google Chrome on Windows and is a pain in the *ss.
