### ISSUE TITLE
word-break

### ISSUE THREAD

**Issue by limenet** [chriscoyier/CSS-Tricks-v10#20] opened 2012-09-06 15:38 UTC
IMO, the word-break you use for body, is very distracting when reading a paragraph, when a word like "of" is like this

```
[...] o<newline>f[...]"
```

In this [screenshot](http://grab.by/fTUS), only one line is - for me - "correctly" broken, the rest looks kinda strange...
sorry for picking on a little detail in such a great design!

_for the record, I'm using Aurora 17 on Win 7 x64_

**Comment by denisew** [comment] 2012-09-06 16:04
I have the same issue FF, Mac, but not in Chrome

**Comment by jpeacock-zenoss** [comment] 2012-09-06 17:07
Seems like FF (both FF 15 and Aurora 17) have bad word break behavior.  Disabling `-moz-hyphens: auto` (using Firebug) seems to shift the break in some words to the correct hyphenating position, but many are still incorrect.  And, there's no actual hyphenation symbol at all where the breaks occur.

**Comment by jtojnar** [comment] 2012-09-06 18:01
Duplicate of #9

**Comment by chriscoyier** [comment] 2012-09-06 21:21
Firefox on non-mac is sucking at this so I removed it.

**Closed as completed by chriscoyier** 2012-09-06 21:21 UTC
