### ISSUE TITLE
Icon Fonts not working in Latest Firefox on Lion

### ISSUE THREAD

**Issue by artlawry** [chriscoyier/CSS-Tricks-v10#15] opened 2012-09-06 15:09 UTC
reference to the font family "Entypo" seems to be behaving local-only. As I don't have Entypo, I just see the default serif font (k, 9, Q, etc.).

**Comment by OllyHodgson** [comment] 2012-09-06 16:07
This is a duplicate of issue #2.

**Comment by chriscoyier** [comment] 2012-09-06 16:08
Fixed.

**Closed as completed by chriscoyier** 2012-09-06 16:08 UTC
